#
# EcoPets
# by Auxilor
#

discover-recipes: true

gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111101111"
      - "111111111"
      - "100000001"
      - "100000001"
      - "100000001"
      - "101000111"

  pet-area:
    top-left:
      row: 3
      column: 2
    bottom-right:
      row: 5
      column: 8

  pet-info:
    row: 1
    column: 5

    no-active:
      name: "&cNo Active Pet"
      lore:
        - ""
        - "&cYou do not currently have a pet active"
        - "&fPick one from the options below!"
        - ""
      item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19

    active:
      name: "%pet% &fLvl. &a%level%"
      lore:
        - "%description%"
        - "&f"
        - "&fEffects:"
        - "%effects%"
        - ""
        - "&fProgress:"
        - "&8» &e%percentage_progress%%"
        - "&8» &e%current_xp%&8/&7%required_xp% &fXP"
        - ""
        - "&eClick to view Level Progression!"

  pet-icon:
    name: "%pet% &fLvl. &a%level%"
    lore:
      - "%description%"
      - "&f"
      - "&fEffects:"
      - "%effects%"
      - ""
      - "&fProgress:"
      - "&8» &e%percentage_progress%%"
      - "&8» &e%current_xp%&8/&7%required_xp% &fXP"

    active-lore:
      - ""
      - "&cThis pet is already active!"

    not-active-lore:
      - ""
      - "&eClick to activate this pet!"

    click:
      sound: ui_button_click
      pitch: 1

  prev-page:
    item: arrow
    name: "&fPrevious Page"
    location:
      row: 6
      column: 4

  next-page:
    item: arrow
    name: "&fNext Page"
    location:
      row: 6
      column: 6

  close:
    item: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

  deactivate-pet:
    item: player_head texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTRiZDlhNDViOTY4MWNlYTViMjhjNzBmNzVhNjk1NmIxZjU5NGZlYzg0MGI5NjA3Nzk4ZmIxZTcwNzc2NDQzMCJ9fX0=
    name: "&cDeactivate Pet"
    location:
      row: 6
      column: 2

level-gui:
  rows: 6

  mask:
    # The way the mask works is by having a list of materials
    # And then a pattern to use those materials.

    # The pattern is the rows in the GUI
    # Each line must be 9 long, and the amount of rows should be the amount of rows in the GUI
    # A zero represents nothing
    # A 1 represents the first material
    # A 2 represents the second material
    # And so on, you can add up to 9.

    materials:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"
      - "111111111"

  progression-slots:
    # To set the order of the pattern,
    # Use 1-9 and then a-z: a goes after 9.
    pattern:
      - "109ab0jkl"
      - "2080c0i0m"
      - "3070d0h0n"
      - "4560efg0o"
      - "00000000p"
      - "00000000q"

    # If the amount of the item should be the level
    level-as-amount: true

    prev-page:
      material: arrow
      name: "&fPrevious Page"
      location:
        row: 6
        column: 4

    next-page:
      material: arrow
      name: "&fNext Page"
      location:
        row: 6
        column: 6

    close:
      material: barrier
      name: "&cClose"
      location:
        row: 6
        column: 5

    unlocked:
      item: lime_stained_glass_pane
      name: "%pet% &fLvl. &a%level%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&aUNLOCKED"
    in-progress:
      item: yellow_stained_glass_pane
      name: "%pet% &fLvl. &a%level%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"
        - "&f"
        - "&fProgress:"
        - "&8» &e%percentage_progress%%"
        - "&8» &e%current_xp%&8/&7%required_xp% &fXP"
    locked:
      item: red_stained_glass_pane
      name: "%pet% &fLvl. &a%level%"
      lore:
        - "&f"
        - "&fRewards:"
        - "%rewards%"

  close:
    material: barrier
    name: "&cClose"
    location:
      row: 6
      column: 5

pet-entity:
  name: "%player%&f's %pet%&f (Lvl. %level%)"

level-up:
  message:
    enabled: true
    message:
      - "&f"
      - " &#d977c2You levelled up your %pet%&#d977c2 pet to &eLevel %level%&#d977c2!"
      - "&f"
      - " &#d977c2&lREWARDS:"
      - " %level_up_messages%"
      - "&f"
  sound:
    # If a sound should be played
    enabled: true
    # The sound that should be played
    id: entity_player_levelup
    # Pitch between 0.5 and 2
    pitch: 1.3

cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford-type:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

point-names: # If you have point names that look ugly (eg g_souls) then you can map them to nice names to be shown to players.
  example_point: "Nicely Formatted Point"

use-faster-move-trigger: true # Disable if you want move trigger to detect sub-1-block movements
raytrace-distance: 80 # The distance that alt_click should check for a location

potions:
  icon:
    permanent: true
    triggered: true
  ambient:
    permanent: false
    triggered: true
  particles:
    permanent: false
    triggered: true

share-configs: true # If your configs are allowed to be used to gather data and improve the plugin. Nothing identifying (IP, Name, etc) is shared.